- name: download file repository zabbix repository
  ansible.builtin.get_url:
    url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu24.04_all.deb"
    dest: /tmp


- name: install the zabbix repository
  ansible.builtin.apt:
    deb: /tmp/zabbix-release_latest+ubuntu24.04_all.deb
    

- name: update cache repository
  ansible.builtin.apt:
    update_cache: yes


- name: install zabbix packages
  ansible.builtin.apt:
    name:
      - zabbix-agent2
      - zabbix-agent2-plugin-*
    state: present  

- name: correct config file zabbix agent2 
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: "^Server="
    line: Server=192.168.4.33

- name: enable and restart zabbix-agent2
  systemd:
    name: zabbix-agent2
    enabled: true
    masked: no
    state: restarted    