---
- name: Устанавливаем filebeat
  apt:
    deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.15.1-amd64.deb"

- name: copy conf file
  template:
    src: ./templates/filebeat.j2
    dest: /etc/filebeat/filebeat.yml

- name: enable and restart filebeat
  systemd:
    name: filebeat
    enabled: true
    daemon_reload: true
    state: restarted