---
- name: Установка Elastic
  become: true
  hosts: elasticserv
  roles:
    - elasticsearch

- name: "Install Kibana"
  become: true
  hosts: kibanaserv
  roles:
    - kibana

- name: "Install Nginx, filebeat"
  hosts: web
  become: true
  roles:
    - nginx
    - filebeat

- name: "zabbix_agent"
  become: true
  hosts: web, log
  roles:
    - zabbix_agent  

- name: "install zabbix server"
  become: true
  hosts: zabbix
  roles: 
    - zabbix      